export enum CardState{
  DEFAULT = "DEFAULT",
  FLIPPED = "FLIPPED",
  MATCHED = "MATCHED",
  FLIPPEDTODEFAULT = "FLIPPEDTODEFAULT",
  FLIPPEDTOMATCHED =" FLIPPEDTOMATCHED",
  DEFAULTTOFLIPPED = "DEFAULTTOFLIPPED"
}
